export default {
    ACTION_CODE: {
		CREATE_USER: 'CREATE_USER',
		UPDATE_USERS: 'UPDATE_USERS',
		DELETE_USER: 'DELETE_USER',
		GET_USERS: 'GET_USERS',
		CREATE_QR: 'CREATE_QR',
		CREATE_WORKDAYS: 'CREATE_WORKDAYS',
		GET_WORKDAYS: 'GET_WORKDAYS',
		CREATE_REPORTS: 'CREATE_REPORTS',
		GET_REPORTS: 'GET_REPORTS',
		UPDATE_REPORTS: 'UPDATE_REPORTS',
		DELETE_REPORTS: 'DELETE_REPORTS',
		CREATE_LEAVES: 'CREATE_LEAVES',
		UPDATE_LEAVES: 'UPDATE_LEAVES',
		GET_LEAVES: 'GET_LEAVES',
		GET_TOTAL_HOUR_WORK: 'GET_TOTAL_HOUR_WORK'
	}
};